export const SET_SEARCH_GIF_RESULT = 'SET_SEARCH_GIF_RESULT';
export const ADD_SEARCH_GIF_RESULT = 'ADD_SEARCH_GIF_RESULT';
export const SEARCH_GIF_STARTED = 'SEARCH_GIF_STARTED';
export const SEARCH_GIF_FINISHED = 'SEARCH_GIF_FINISHED';